### ISSUE TITLE
Cuchi plugin

### ISSUE THREAD

**Issue by gustavobonassa** [kammradt/awesome-cuchi#1]
we need a browser plugin to transform all images in cuchi, like this:
https://chrome.google.com/webstore/detail/ncage/mpnfndnehgmmonhfcfdnaemdeokofgaf?hl=pt-BR

![image](https://user-images.githubusercontent.com/26508215/156487790-044a6209-f8f1-41e8-949a-1f489585ef22.png)

**Comment by kammradt** [comment]
I can work on that...

**Comment by kammradt** [comment]
I'll close this one since I already added this ideia to the README
