### ISSUE TITLE
Cuchi face as a cli program

### ISSUE THREAD

**Issue by danielSbastos** [kammradt/awesome-cuchi#3]
Wouldn't it be nice if there was a cli for Cuchi where it could show our idol's face in an ASCII art? I can work on that

**Comment by kammradt** [comment]
That's a really good ideia!  
I'll try it today and if it turns out to be a little harder than expected, we can do a pair on it

**Comment by danielSbastos** [comment]
@kammradt, sounds awesome!

**Comment by kammradt** [comment]
@danielSbastos feel free to take a look

https://github.com/kammradt/ascuchiii

**Comment by kammradt** [comment]
I'll mark this as done after updating awesome-cuchi

**Comment by danielSbastos** [comment]
@kammradt, I am screaming with happiness for the brilliant concatenation o ASCII and Cuchi, it is truly a piece of art of a great developer and artist as you.

Nonetheless, I tried using `ascuchiii` but faced the following error:

```rb
Traceback (most recent call last):
	6: from /usr/local/bin/ascuchiii:23:in `<main>'
	5: from /usr/local/bin/ascuchiii:23:in `load'
	4: from /var/lib/gems/2.7.0/gems/ascuchiii-1.2/bin/ascuchiii:5:in `<top (required)>'
	3: from /var/lib/gems/2.7.0/gems/ascuchiii-1.2/bin/ascuchiii:5:in `require_relative'
	2: from /var/lib/gems/2.7.0/gems/ascuchiii-1.2/lib/ascuchiii.rb:3:in `<top (required)>'
	1: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
/usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require': cannot load such file -- artii (LoadError)
```

**Comment by kammradt** [comment]
Current version is 1.3   

Maybe `gem uninstall ascuchiii && gem install ascuchiii && rbenv rehash` will do the trick

**Comment by danielSbastos** [comment]
@kammradt, doesn't seem to do the trick :cry: 

![image](https://user-images.githubusercontent.com/21130697/157339911-a9455f30-6a46-4317-940b-620d10fbcd67.png)


I'll try to debug a bit more here on my end (to check if it isn't something local)
